### ISSUE TITLE
Path

### ISSUE THREAD

**Issue by JuliCou** [swastiknath/iot_ud_3#1]
Hi,

I thank you so much for this project. It is exactly what I have been looking for. It is clean and neat with a wonderful README. Everything is working perfectly.

I just want to point that in the README, you missed a "0" for the download of : face-detection-adas-binary-0001

Personnally, I have an SSL error with the downloader.py. I decided to download it directly from https://download.01.org/ (if it can help others).

Finally, in the demonstration commands, I believe there is a mistake with the paths (face-detection-retail-0005).

Thank you for sharing :)
I will go through your other projects.

**Comment by swastiknath** [comment]
Thank you @JuliCou for pointing the fixes. I have updated the documentation [#ef38f89
](https://github.com/swastiknath/iot_ud_3/commit/ef38f89c05430934e5d593c90cf7b318a15f7154) with your prescribed fixes. You are welcome to submit further Pull requests if you find further issues around anything. 
Regards.
